[workspace]
authors = ["Convolutio <79534557+Convolutio@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "ga-llm-cat"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
requests = ">=2.32.5,<3"
